// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQs5BgF2MX_50qU9WmUwLFJzVWdQgXhhA',
    appId: '1:371004320874:web:8ab3a6e1376330af62ae13',
    messagingSenderId: '371004320874',
    projectId: 'peto-fd14b',
    authDomain: 'peto-fd14b.firebaseapp.com',
    storageBucket: 'peto-fd14b.firebasestorage.app',
    measurementId: 'G-0HWY9W2CB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2kABjmVun4hONN8CYW7c2YlkZWHWBS_s',
    appId: '1:371004320874:android:91cb9753ef64e0ea62ae13',
    messagingSenderId: '371004320874',
    projectId: 'peto-fd14b',
    storageBucket: 'peto-fd14b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8xO_FKq920ZGevDT5qiRwzTjYQrtvTII',
    appId: '1:371004320874:ios:5b31b8ae22d9d54a62ae13',
    messagingSenderId: '371004320874',
    projectId: 'peto-fd14b',
    storageBucket: 'peto-fd14b.firebasestorage.app',
    iosBundleId: 'com.example.peto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8xO_FKq920ZGevDT5qiRwzTjYQrtvTII',
    appId: '1:371004320874:ios:5b31b8ae22d9d54a62ae13',
    messagingSenderId: '371004320874',
    projectId: 'peto-fd14b',
    storageBucket: 'peto-fd14b.firebasestorage.app',
    iosBundleId: 'com.example.peto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQs5BgF2MX_50qU9WmUwLFJzVWdQgXhhA',
    appId: '1:371004320874:web:1f84938d1c0e4d3162ae13',
    messagingSenderId: '371004320874',
    projectId: 'peto-fd14b',
    authDomain: 'peto-fd14b.firebaseapp.com',
    storageBucket: 'peto-fd14b.firebasestorage.app',
    measurementId: 'G-5Z2KP75FB6',
  );
}
